//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanAzzopardi.TranslatorExtensionPackage {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class LanguageSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LanguageSettings defaultInstance = ((LanguageSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LanguageSettings())));
        
        public static LanguageSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dutch")]
        public string LangFrom {
            get {
                return ((string)(this["LangFrom"]));
            }
            set {
                this["LangFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string LangTo {
            get {
                return ((string)(this["LangTo"]));
            }
            set {
                this["LangTo"] = value;
            }
        }
    }
}
